RECEIVER_DOMAIN     =   "@synergex-systems.com"
SENDER_DOMAIN       =   "@bluecitycapital.us"
receiver_name       =   "Synergex Systems Limited"
receiver_email      =   f"comms{RECEIVER_DOMAIN}"
sender_name         =   "Blue City Capital Technologies, Inc"
sender_email        =   f"notifications{SENDER_DOMAIN}"