import email_auth
import uuid
import os
import settings_mapper

def company_signoff() -> None:
    return f"""
    Yours sincerely<br>
    <b>{settings_mapper.MESSAGING_METADATA["SENDER_NAME"]}</b><br>
    The {settings_mapper.MESSAGING_METADATA["SENDER_DEPARTMENT"]} Team<br>
    {settings_mapper.MESSAGING_METADATA["SENDER_EMAIL"]}<br><br>
    return
    """

github_owner = settings_mapper.GITHUB_CONSTANTS["OWNER"]

def send_message(latest_commit_data:dict = None, changed_repo_list:list = None, github_owner:str = None) -> None:
    """
    Sends an email containing a list of updated remote repositories, contaning (but not limited to) the latest commit `sha`, the date of the commit and the latest commit message.

    Args:
        latest_commit_date(dict): A list of data pertaining to each remote repository, 
        changed_repo_list(list): A list of changed local repositories,
        github_owner(str): Denotes the owner of the GitHub account - this is retrieved from the `.env` file. 
    Notes:
    -
    The SMTP credentils will then be checked via the `smtp_auth` module. For obvious reason if autnehtication fails, then a message will not be send, however, a support ticket will be generated in the FreshDesk portal. 
    """
    
    GITHUB_URL      =   "https://github.com/{owner}"
    github_url      =   GITHUB_URL.format(owner=github_owner)
    custom_subject  =   "Github Commit Report"
    
    resource_data_table = ""
    for data in latest_commit_data:
            resource_data_table += f"""
            ========================================================================<br>
            <table border="0" cellpadding="5" cellspacing="0" style="border-collapse: collapse; text-align: left;">
                <tr>
                    <th>Secure Hash Algorithm (SHA):</th>
                    <td>{data["sha"][:7]}</td>
                </tr>
                <tr>
                    <th>Repository Name:</th>
                    <td>{data['repo']}</td>
                </tr>
                <tr>
                    <th>Commit Date:</th>
                    <td>{data['date']}</td>
                </tr>
                <tr>
                    <th>Commit message:</th>
                    <td>{data['msg']}</td>
                </tr>
                <tr>
                    <th>Author ID:</th>
                    <td>{data['id']}</td>
                </tr>
            </table>
            """    
            
    message_body = f"""
    Dear {settings_mapper.MESSAGING_METADATA["REQUESTER_NAME"]}<br><br>
    We are writing to you because you have a new commit uploaded to your GitHub repository.
    Check it out by visiting your GitHub account at {github_url}<br><br>
    {resource_data_table}
    ========================================================================<br>
    The local directories which have been changed since the last commit are {changed_repo_list}<br><br>
    * You must be logged into the GitHub Repository in order to see the list of commits within the API call.<br><br>
    {company_signoff()}
    """
    if not email_auth.smtp_auth(message_body, custom_subject):
         return None

    return None

def generate_incident_uuid() -> str:
    return f"""{uuid.uuid4()}"""

def freshdesk_inop_notification(custom_message:str) -> None:
    """
    This method is invoked in the event that a support ticket is unable to generated.
    Instead, a `UUID` is generated to be used as an error identification number.
    This replaces the support ticket which would have normally been generated by the FreskDesk system. 
    Returns:
        None: 
    """  
    
    incident_uuid   =   generate_incident_uuid()
    custom_subject  =   "Error Generating Support Ticket."
    
    freshdesk_inop_text_body = f"""
        Dear {settings_mapper.MESSAGING_METADATA["REQUESTER_NAME"]}<br><br>
        We are writing to you because our support ticketing system is either currently offline or our credentials are invalid.
        ========================================================================<br>
        <table border="0" cellpadding="5" cellspacing="0" style="border-collapse: collapse; text-align: left;">
            <tr>
                <th>Freshdesk Inoperative Reason:</th>
                <td>{custom_message}</td>
            </tr>
            <tr>
                <th>Incident reference Number</th>
                <td>{incident_uuid}</td>
            </tr>
        </table>
        ========================================================================<br><br>
        {company_signoff()}
    """

    print(freshdesk_inop_text_body)
    if not email_auth.smtp_auth(freshdesk_inop_text_body, custom_subject):
         return None

    return None